# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('contact', models.IntegerField(default=0)),
                ('address', models.CharField(default=b'', max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('designation', models.CharField(default=b'', max_length=30)),
                ('experience', models.IntegerField(default=0)),
                ('skills', models.CharField(default=b'', max_length=200)),
                ('emp_rating', models.FloatField(default=0)),
            ],
        ),
    ]
