# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170803_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emp_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
