# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170901_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(default=b'', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default=b'', max_length=1000),
        ),
    ]
