# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170901_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.IntegerField(choices=[(0, b'Supervisor'), (1, b'Project Manager'), (2, b'Developer'), (3, b'Client')], default=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, default=b'', null=True),
        ),
    ]
