# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170925_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectuser', models.CharField(default=b'', max_length=1000)),
            ],
        ),
    ]
