# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='file',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='publish',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='commits',
            name='file',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='commits',
            name='publish',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='modules',
            name='terminate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='terminate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='publish',
            field=models.DateTimeField(),
        ),
    ]
