# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20170729_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='manager_id',
            field=models.IntegerField(default=0),
        ),
    ]
