# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_projects_manager_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Commits',
            new_name='Commit',
        ),
        migrations.RenameModel(
            old_name='Modules',
            new_name='Module',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
