# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20170730_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='name',
            field=models.CharField(default='commit0', max_length=500),
        ),
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.CharField(default='module0', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='project0', max_length=250),
        ),
    ]
