# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20170730_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='terminate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='terminate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
