# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20170730_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='file',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
