# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20170818_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
